server:
  port: 8095

spring:
  banner:
    location: classpath:/banner/banner.txt
    
  datasource:    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: JWRTALLER
    password: 123456